/**
 * models.js
 * ─────────────────────────────────────────────
 * Data model definitions for the Aria app.
 *
 * These are NOT classes — they're factory functions that return
 * plain JS objects with default values. Think of them as blueprints.
 *
 * Why factory functions instead of classes?
 * They're simpler, easier to spread/merge, and work well with Supabase.
 *
 * Usage:
 *   import { createGoal, createRoutine } from '../models/models';
 *   const goal = createGoal({ title: 'Lose 5kg', userId: 'abc' });
 * ─────────────────────────────────────────────
 */

import dayjs from 'dayjs';

// ─── User ─────────────────────────────────────
/**
 * createUser
 * Represents a registered app user.
 * Stored in Supabase 'users' table.
 */
export function createUser(overrides = {}) {
  return {
    id:           null,   // UUID from Supabase auth
    email:        '',
    display_name: '',
    avatar_url:   null,

    // User preferences — affect AI personalisation
    preferences: {
      wakeTime:   '07:00',
      sleepTime:  '23:00',
      workDays:   ['mon', 'tue', 'wed', 'thu', 'fri'],
      constraints: [],    // e.g. ["no exercise after 8pm", "vegetarian"]
    },

    created_at: dayjs().toISOString(),
    ...overrides,
  };
}

// ─── Goal ─────────────────────────────────────
/**
 * createGoal
 * A high-level goal the user wants to achieve.
 * Goals inform which routines the AI suggests.
 * Stored in Supabase 'goals' table.
 */
export function createGoal(overrides = {}) {
  return {
    id:          null,    // UUID, generated by Supabase
    user_id:     null,    // FK → users.id
    title:       '',      // e.g. "Lose 5kg"
    description: '',
    category:    'health',// matches ROUTINE_CATEGORIES ids
    target_date: null,    // ISO date string or null
    is_active:   true,
    progress:    0,       // 0–100 percentage
    created_at:  dayjs().toISOString(),
    ...overrides,
  };
}

// ─── Routine ──────────────────────────────────
/**
 * createRoutine
 * A named collection of tasks the user does repeatedly.
 * e.g. "Morning Skincare Routine" with 5 steps.
 * Stored in Supabase 'routines' table.
 */
export function createRoutine(overrides = {}) {
  return {
    id:          null,
    user_id:     null,
    title:       '',
    description: '',
    category:    'health',
    tasks:       [],       // array of RoutineTask objects (see below)

    // Scheduling
    frequency:   'daily',  // 'daily' | 'weekdays' | 'weekends' | 'custom'
    days:        ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
    start_time:  '08:00',  // default start time

    // Stats (updated after each completion)
    streak:           0,
    total_completions: 0,
    last_completed:   null,

    is_active:   true,
    ai_generated: false,   // true if Aria created this
    created_at:  dayjs().toISOString(),
    ...overrides,
  };
}

// ─── Routine Task ─────────────────────────────
/**
 * createRoutineTask
 * A single step within a routine.
 * e.g. "Apply cleanser — 2 minutes"
 */
export function createRoutineTask(overrides = {}) {
  return {
    id:           null,
    routine_id:   null,   // FK → routines.id
    title:        '',
    notes:        '',     // optional tip or instruction
    duration_mins: 5,
    order:        0,      // display order within the routine
    is_completed: false,  // reset each day
    ...overrides,
  };
}

// ─── Schedule Task ────────────────────────────
/**
 * createScheduleTask
 * A time-blocked task on the calendar for a specific day.
 * Can be linked to a routine or be standalone.
 * Stored in Supabase 'schedule_tasks' table.
 */
export function createScheduleTask(overrides = {}) {
  return {
    id:          null,
    user_id:     null,
    routine_id:  null,    // optional FK → routines.id
    title:       '',
    date:        dayjs().format('YYYY-MM-DD'),
    start_time:  '09:00',
    end_time:    '09:30',
    color:       '#6A5ACD',
    is_completed: false,
    created_at:  dayjs().toISOString(),
    ...overrides,
  };
}

// ─── Chat Message ─────────────────────────────
/**
 * createChatMessage
 * A single message in the AI chat.
 * Stored in Supabase 'chat_history' table.
 */
export function createChatMessage(overrides = {}) {
  return {
    id:        null,
    user_id:   null,
    role:      'user',     // 'user' | 'model'
    text:      '',
    timestamp: dayjs().toISOString(),
    metadata:  null,       // optional: store parsed routine JSON here
    ...overrides,
  };
}
